# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f50d247913d7872d2b456b5fafefa6152be6796c2fabbe6ff10a94bbff45d5f1d6def9fe9fe1e582b0ac9a2ce35c20b27cb923b63321694a687f93ab59520bc

test:
  secret_key_base: 650ecdce1e3515130577722091e9c3e965b44a71bf20f9ac991e7a69684ee20fcc0e8d40a386bfe6683ebe18c22972323ffd5deb44fd81737560c016879cd847

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
